// =============================================================================
// comandos.js — Comandos de operación: Esclusa de Gatún
// =============================================================================

window.normalizarPlanta = function() {
var conf=confirm('⚠️ ¿Restablecer la planta a su ESTADO ORIGINAL?');if(conf){var ab=['SGE-8-A','SCAISSON-WEST','S23-W4-C','SCAISSON-EAST','S23-E4-A','SGW-8-B','S23-W6-1','S23-W6','SGE-6E-GW-6E-2','SGE-7E-GW-7E-1','S23-E8-23-W8-B','S23-E7-23-W7-B','S23-W3','SWEST-CAISSON','SCAISSON-SW-RM1','SGE-5E-GW-5E1','SGW-12'];var sel={'SEL-TR444UNIT-A':'NC','SEL-TR444UNIT-B':'NO','SEL-TR440UNIT-A':'NC','SEL-TR440UNIT-B':'NO'};var eq=document.querySelectorAll('[data-estado]');eq.forEach(function(el){var id=el.id||'';var rect=document.getElementById('rect_'+id)||el.querySelector('rect')||el;if(!rect)return;if(sel[id]){var e=sel[id];el.setAttribute('data-estado',e);var c=(e==='NC')?'#00FF00':'#FFFF00';rect.style.fill=c;rect.setAttribute('fill',c);}else{var eAb=ab.includes(id);var e=eAb?'ABIERTO':'CERRADO';el.setAttribute('data-estado',e);var c='#00FF00';if(eAb){var esS=id.startsWith('S')&&!id.startsWith('SEL');c=esS?'#FFA500':'#FF0000';}rect.style.fill=c;rect.setAttribute('fill',c);}});if(window.actualizarGatun)window.actualizarGatun();alert('✅ MANIOBRA COMPLETADA:\nEstado original de la planta restablecido.');}};

window.resetearPlanta = function() {
var confirmar=confirm('⚠️ ATENCIÓN:\n\n¿Seguro que desea ABRIR 🔴 TODOS los equipos?');if(confirmar){var cont=0;var equipos=document.querySelectorAll('[data-estado]');equipos.forEach(function(el){var id=el.id||'';if(id.startsWith('SEL-'))return;el.setAttribute('data-estado','ABIERTO');var esSecc=id.startsWith('S');var col=esSecc?'#FFA500':'#FF0000';var rect=document.getElementById('rect_'+id)||el.querySelector('rect')||el;if(rect){rect.style.fill=col;rect.setAttribute('fill',col);}cont++;});if(window.actualizarGatun)window.actualizarGatun();alert('✅ MANIOBRA COMPLETADA\n'+cont+' equipos han sido abiertos 🔴.');}};
